name: Mirror to Deploy Repo

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Mirror repository
        run: |
          git config --global user.name "mirror-bot"
          git config --global user.email "mirror-bot@example.com"

          git remote add mirror https://x-access-token:${{ secrets.MIRROR_TOKEN }}@github.com/shawez-0422/IvaAI-backend.git
          git push mirror master --force
