name: Mirror to Deploy Repo

on:
  push:
    branches:
      - master

jobs:
  mirror:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Prepare backend for mirror
        run: |
          mkdir deploy
          cp -r backend/IvaAI/* deploy/
          cd deploy
          git init
          git checkout -b master

      - name: Push backend to mirror repo
        env:
          TOKEN: ${{ secrets.MIRROR_TOKEN }}
        run: |
          cd deploy
          git config user.name "mirror-bot"
          git config user.email "mirror-bot@example.com"

          git add .
          git commit -m "${{ github.event.head_commit.message }}"

          git remote add origin https://x-access-token:$TOKEN@github.com/shawez-0422/IvaAI-backend.git
          git push origin master --force
